### ISSUE TITLE
Push Git Tags when making a Release

### ISSUE THREAD

**Issue by Pascalmh** [VPenkov/okayNav#14]
By pushing the git tags you allow bower-Users to not run into major release updates without noticing. Currently you can `bower install okaynav` but you can not specify which version you want, that's bad.

https://help.github.com/articles/creating-releases/

**Comment by VPenkov** [comment]
I guess it's worth considering this.

Currently I'm trying to be conservative about pushing code and tend to do this when I'm done with something and it's tested. Also, the plugin is currently in its early versions and it's likely that issues will pop out so I wouldn't want to let people download older versions because the latest version is supposed to be the best one.

Additionally, I tend to add options to disable any new features (i.e. the swipe implementation) because I'm aware that some people may find them inapplicable or even problematic.

And this is especially true about the current version - I absolutely do not want people to use the older versions, I should have called them beta.

**Comment by Pascalmh** [comment]
Sure everyone should use the newest version of a software as they are supposed to be improve.

I am using this with Continuous Deployment. So on every merge into master the Server does a `bower install` - as you do not push git tags currently I can not tell the Continuous Deployment Server which version to use and it just gets the latest Version.

What happened now is:
- I install okaynav via bower locally (okaynav 1.x.x)
- I push changes to our Staging Server
  - Server does `bower install` - everything is fine (okaynav 1.x.x is used)
- Everyone likes the changes, tests complete successful
- Meanwhile you release a new Version (okaynav 2.x.x)
- We merge my changes into master
  - server does `bower install` - installs okaynav 2.x.x - this has breaking changes, production environment is broken
